version: '2'
services:
    teste1-app:
        image: teste1
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://teste1-mysql:3306/teste1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    teste1-mysql:
        extends:
            file: mysql.yml
            service: teste1-mysql
